version: "2.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/node/app
      - /node/app/node_modules # hide the host node_modules
